DROP TABLE IF EXISTS PUBLIC.ORDER_ITEMS;

DROP TABLE IF EXISTS PUBLIC.SKUS;

DROP TABLE IF EXISTS PUBLIC.PRODUCT_SIZES;

DROP TABLE IF EXISTS PUBLIC.PRODUCT_COLORS;

DROP TABLE IF EXISTS PUBLIC.COLORS;

DROP TABLE IF EXISTS PUBLIC.PRODUCTS;

DROP TABLE IF EXISTS PUBLIC.ORDERS;

DROP TABLE IF EXISTS PUBLIC.CUSTOMERS;

DROP TYPE PUBLIC.ORDER_STATUS;

DROP INDEX CONCURRENTLY idx_fk_product_colors_product_id;

DROP INDEX CONCURRENTLY idx_fk_product_colors_color_id;

DROP INDEX CONCURRENTLY idx_fk_skus_product_color_id;

DROP INDEX CONCURRENTLY idx_skus_product_color_price;

DROP INDEX CONCURRENTLY idx_products_name;

DROP INDEX CONCURRENTLY idx_products_code_trgm;

DROP INDEX CONCURRENTLY idx_products_name_trgm;

DROP INDEX CONCURRENTLY idx_colors_name_lower;

DROP INDEX CONCURRENTLY idx_products_name_id;

DROP INDEX CONCURRENTLY idx_product_colors_composite;

DROP INDEX CONCURRENTLY idx_colors_name;

DROP INDEX CONCURRENTLY idx_fk_order_items_order_id;

DROP INDEX CONCURRENTLY idx_fk_order_items_sku_id;

DROP INDEX CONCURRENTLY idx_fk_orders_customer_id;

DROP INDEX CONCURRENTLY idx_customers_name_trgm;

DROP INDEX CONCURRENTLY idx_customers_email_trgm;

DROP EXTENSION IF EXISTS pg_trgm;

ANALYZE orders;

ANALYZE order_items;

ANALYZE customers;

ANALYZE products;

ANALYZE colors;

ANALYZE product_colors;

ANALYZE skus;